<?php require 'templates/header.phtml'; ?>

<div class="mt-5 w-25 mx-auto">
    <form method="POST" action="addProducto">
        <div class="form-group">
            <label class="text-dark" for="nombre">Nombre</label>
            <input type="text" required class="form-control" id="nombre" name="nombre" aria-describedby="userHelp">
        </div>
        <div class="form-group">
            <label class="text-dark" for="descripcion">Imagen</label>
            <input type="text" required class="form-control" id="imagen" name="imagen">
        </div>
        <div class="form-group">
            <label class="text-dark" for="categoria">Categoria</label>
            <select name="categoria">
                <?php foreach ($categorias as $categoria): ?>
                    <option value="<?= $categoria->id ?>"><?= $categoria->marca ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="form-group">
            <label class="text-dark" for="precio">Modelo</label>
            <input type="number" required class="form-control" id="modelo" name="modelo">
        </div>
        <div class="form-group">
            <label class="text-dark" for="precio">Motor</label>
            <input type="text" required class="form-control" id="motor" name="motor">
        </div>
        <div class="form-group">
            <label class="text-dark" for="precio">Kilometros</label>
            <input type="number" required class="form-control" id="kilometros" name="kilometros">
        </div>
        <div class="form-group">
            <label class="text-dark" for="precio">Detalles</label>
            <input type="text" required class="form-control" id="detalles" name="detalles">
        </div>
        <div class="form-group">
            <label class="text-dark" for="precio">Precio</label>
            <input type="number" required class="form-control" id="precio" name="precio">
        </div>
        <?php if (isset($error)): ?>
            <div class='alert alert-danger' role='alert'>
                <?= $error ?>
            </div> 
        <?php endif; ?>
       
        <button type="submit" class="btn btn-primary mt-3">Agregar</button>
    </form>
</div>

<?php require 'templates/footer.phtml'; ?>