<section>
    <h1 class="text-center text-white">Seleccione la marca: </h1>
    <div class="productos-container">
        <ul class="productos">
            <?php foreach ($marcas as $marca): ?> 
                <li class="list-group-item">
                    <a class="btn-solicitud text-decoration-none text-white     " href="../TPE2/productos/<?= $marca->marca ?>"> 
                        <?= $marca->marca ?> 
                    </a>
                    <?php if (AuthHelper::verify()): ?>
                    <a href="./templates/delete/<?= $marca->id ?>">
                        <button class="btn btn-danger">Eliminar</button>
                    </a>
                    <?php endif; ?>
                </li>
            <?php endforeach ?>
        </ul>
    </div>
</section>
<a class="VolverBTN" href="home">
    <button class="btn_volver">Volver</button>
</a>
<?php if (AuthHelper::verify()): ?>
<a href="./addMarca">
    <button class="btn btn-success">Agregar</button>
</a>
<?php endif; ?>