<section>
    <h1 class="text-center text-dark">Seleccione la marca: </h1>
    <div class="productos-container">
        <ul class="productos">
            <?php foreach ($marcas as $marca): ?> 
                <li class="list-group-item">
                    <?php if (AuthHelper::verify()): ?>
                        <a href="./showUpdateMarca/<?= $marca->id ?>"><button class="btn_editar">Editar</button></a>
                    <?php endif; ?>
                        <a class="btn-solicitud text-decoration-none text-white " href="../TPE2/productos/<?= $marca->id ?>"><?= $marca->marca ?></a>
                    <?php if (AuthHelper::verify()): ?>
                        <a href="./deleteMarca/<?= $marca->id ?>"><button class="btn btn-danger">Eliminar</button></a>
                    <?php endif; ?>
                </li>
            <?php endforeach ?>
        </ul>
    </div>
</section>
<a class="VolverBTN" href="home">
    <button class="btn_volver">Volver</button>
</a>
<?php if (AuthHelper::verify()): ?>
<a href="./addMarca">
    <button class="btn_agregar">Agregar</button>
</a>

<?php endif; ?>