
<footer class="footer">
        <div class="container">
            <div class="footer-content">
                <h1 class="logo">
                    <span class="logo_footer">TANDILMOTORS</span>
                </h1>
                <p>© 2024 Tandilmotors. Todos los derechos reservados.</p>
                <div class="footer-links">
                    <a href="#">Política de privacidad</a>
                    <a href="#">Términos y condiciones</a>
                </div>
                <p class="recaptcha">This site is protected by reCAPTCHA and the Google Privacy Policy and Terms of Service apply.</p>
            </div>
        </div>
    </footer>
</body>