<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <base href="<?= HOME ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="./css/style.css">
    <title>Tandil Motors</title>
</head>

<body>

<!-- Sección de encabezado -->
<header>
        <div class="menu container">
            <a href="#" class="logo">TANDILMOTORS</a>
            <!-- Navegación -->
            <nav class="navbar">
                <ul>
                    <li><a href="../TPE2/home">Inicio</a></li>
                    <li><a href="../TPE2/marcas">Marcas</a></li>
                    <li><a href="../TPE2/categoria">Buscar</a></li>
                </ul>
            </nav>            
        </div>
</header>
