<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <base href="<?= HOME ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="./css/style.css">
    <title>Tandil Motors</title>
</head>

<body>

<!-- Sección de encabezado -->
<header>
        <div class="menu container">
            <a href="../TPE2/home" class="logo">TANDILMOTORS</a>
            <!-- Navegación -->
            <nav class="navbar">
                <div>
                    <ul>
                        <li><a href="../TPE2/home">Inicio</a></li>
                        <li><a href="../TPE2/marcas">Marcas</a></li>
                        <li><a href="../TPE2/categoria">Buscar</a></li>
                        <?php AuthHelper::init();
                            if (!isset($_SESSION['usuario'])): ?>
                            <li><a href="../TPE2/login">Iniciar Sesión</a></li>
                            <?php else: ?>
                            <li class = "btn-danger"><a href="../TPE2/logout">logout</a></li>
                            <?php endif?>
                    </ul>
                </div>
            </nav>            
        </div>
</header>
