<?php require_once 'templates/header.phtml';?>
    <section class = "full">
        <div id="inicio" class="full-inner">
            <div class="content">
                <h1 class="text-dark">Comprá un deportivo 100% verificado por expertos</h1>
                <h3 class="text-dark">TandilMotors ofrece vehículos con garantía técnica y garantía de documentación. Elegís el auto que
                    te
                    gusta, te ayudamos con la transferencia y lo recibís sin moverte de tu casa.</h3>
                <h3 class="text-dark">¡Super seguro, super fácil y super cómodo!</h3>
                
                <nav class="navinicio">
                    <ul>
                        <li><a href="../TPE2/categoria" class="ver">VER AUTOS DISPONIBLES</a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </section>
    <!-- Sección de información -->
    <div class="informacion">
        <!-- Subsección de trazabilidad -->
        <div class="trazabilidad">
            <div class="texto">
                <h1>Autos que tienen trazabilidad</h1>
                <p>TandilMotors es garantía de mantenimiento. Los vehículos en venta fueron usados por empresas y
                    gestionados
                    por RDA Mobility. Esto significa que cuentan con todos los <strong>servicios técnicos</strong>
                    realizados por talleres
                    seleccionados,<strong> repuestos originales, verificación técnica y documentación</strong> al
                    día.
                </p>
                <p>Los autos en stock <strong>no están en circulación </strong> ni son exhibidos a cualquier
                    persona,
                    están bajo nuestro resguardo hasta que se produce la venta</p>
            </div>
            <img src="img/icon-trazabilidad.png" alt="icon-trazabilidad">
        </div>
        <!-- Subsección de simplicidad -->
        <div class="simple">
            <img src="img/icon-simple.png" alt="icon-simple">
            <div class="texto">
                <h1>Lo hacemos más simple</h1>
                <p>Comprar un auto usado dejó de ser algo complejo, con TandilMotors vos sólo te ocupás de elegir el
                    auto.
                    Diseñamos un proceso ágil para que recibas el auto con un <strong>control técnico/administrativo de
                        más de
                        200 puntos </strong> en el lugar que necesites.</p>
            </div>
        </div>
        <!-- Subsección de tranquilidad -->
        <div class="tranquilidad">
            <div class="texto">
                <h1>La tranquilidad y el respaldo que necesitás</h1>
                <p>TandilMotors es una unidad de negocios de RDA Group, grupo que gestiona <strong>más de 10.000
                        vehículos</strong> de flotas corporativas. Nos caracteriza la transparencia y calidad de
                    servicio. Nuestro equipo de
                    profesionales cuenta con amplia experiencia y conocimiento en la <strong>venta de
                        vehículos.</strong></p>
            </div>
            <img src="img/icon-tranquilidad.png" alt="icon-tranquilidad">
        </div>
    </div>
    <!-- Sección de carrusel -->
    <div class="div-carrusel">
        <div class="titulos-carrusel">
            <h1>Comprar auto</h1>
            <h3>Colaboracion con marcas:</h3>
        </div>
        <!-- Carrusel de imágenes de autos -->
        <section class="carrusel">
            <img src="images/logo_toyota.png" alt="audi-a5">
            <img src="images/logo_BMW.png" alt="mercedes-c300">
            <img src="images/logo_ford.png" alt="audi-att">
            <img src="images/logo_volkswagen.png" alt="bmw-m135i">
            <img src="images/logo_audi.png" alt="audi-a7"> 
        </section>
         <!-- Botón para ver más autos disponibles -->
        <nav class="div-disponible">
            <ul>
                <li><a href="../TPE2/categoria" class="btn-disponibles">Consegui el tuyo</a></li>
            </ul>
        </nav>
    </div>
    <!-- Sección de solicitud de información -->
    <div class="solicitar">
        <div class="texto-solicitar">
        <img src="img/icon-solicitar.png" alt="icon-solicitar">
        <h1>¿Buscabas otro auto?</h1>
        <p>Si no encontraste el auto que buscabas te invitamos a completar el formulario con el detalle del vehículo que
            necesitás y nosotros te avisamos cuando ingrese a nuestro stock. RDA gestiona grandes flotas de vehículos
            corporativos y <strong>cuenta con más de 10.000 autos que pronto estarán a la venta.</strong></p>
        </div>
        <!-- Formulario de solicitud -->
        <div class="form-container">
            <form>
                <div class="form-group">
                    <label for="name">Nombre y Apellido:</label>
                    <input type="text" id="name" name="name" required>
                </div>
                <div class="form-group">
                    <label for="phone">Teléfono:</label>
                    <input type="tel" id="phone" name="phone" required>
                </div>
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" id="email" name="email" required>
                </div>
                <!-- Grupo de campos de entrada para marca y modelo -->
                <div class="form-group-inline">
                    <label for="brand">Marca:</label>
                    <input type="text" id="brand" name="brand" required>
                    <label for="model" class="modelo">Modelo:</label>
                    <input type="text" id="model" name="model" required>
                </div>
                <!-- Botón de envío de la solicitud -->
                <button class="btn-solicitud" type="submit">ENVIAR SOLICITUD</button>
            </form>
        </div>        
    </div>
     <!-- Vincula el archivo JavaScript principal -->
    <script src="js/main.js"></script>
</body>
<?php require './templates/footer.phtml';

