
<body>
<div class="bg-light d-flex justify-content-center align-items-center" style="height: 100vh;">
        <div class="">
            <form class = "formulario_login" method="POST" action="auth">
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" required class="form-control" id="email" name="email" aria-describedby="emailHelp">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" required class="form-control" id="password" name="password">
                </div>

                <?php if ($error) : ?>
                    <div class='alert alert-danger' role='alert'>
                        <?= $error ?>
                    </div>
                <?php endif ?>
                <button  type="submit" class="btn_iniciar">Entrar</button>
            </form>
            <a href="../TPE2/home"><button class="btn_volver">Volver a inicio</button></a>
        </div>
    </div>

</body>
</html>