<section>
<h1 class= "text-center text-dark">Seleccione el producto: </h1>
    <div>
        <ul class="productos">
            <?php foreach ($productos as $producto): ?> 
                <li class="list-group-item">
                    <a class="btn-solicitud" href="../TPE2/productoUnico/<?= $producto->ID ?>" class="text-decoration-none text-dark"> <?= $producto->nombre ?> </a>
                    <?php if (AuthHelper::verify()): ?>
                <span>---</span>
                <button class="btn btn-success"><a class="text-white text-decoration-none" href="showUpdateProducto/<?= $producto->ID ?>">Editar </a></button>
                <span>---</span>
                <button class="btn btn-danger"><a class="text-white text-decoration-none" href="deleteProducto/<?= $producto->ID ?>" >Eliminar </a></button>
            <?php endif; ?>
            <?php endforeach ?>
        </ul>
    </div>
</section>
<a class ="VolverBTN" href="home"><button  class="btn_volver"><-volver</button></a>
<?php if (AuthHelper::verify()): ?>
<a href="./showAddProducto">
    <button class="btn btn-success">Agregar</button>
</a>
<?php endif; ?>