<section>
<h1 class= "text-center text-white">Seleccione el producto: </h1>
    <div>
        <ul class="productos">
            <?php foreach ($productos as $producto): ?> 
                <li class="list-group-item">
                    <a class="btn-solicitud" href="../TPE2/producto/<?= $producto->ID ?>" class="text-decoration-none text-dark"> <?= $producto->Nombre ?> </a>
            <?php endforeach ?>
        </ul>
    </div>
</section>
<a href="home"><button  class="btn-solicitud"><-volver</button></a>