<?php
require 'templates/header.phtml';
if (isset($producto)):
    $nombre = $producto->nombre;
    $imagen = $producto->imagen;
    $precio = $producto->precio;
    $categoria = $producto->marca;
    $modelo = $producto->modelo;
    $motor = $producto->motor;
    $kilometros = $producto->kilometros;
    $detalles = $producto->detalles;
?>
  <div class="container mx-auto mt-5">
    <div class="fotos">
      <div class="p-4">
        <h2 class="text-center text-2xl font-bold"><?= $nombre; ?></h2>
        <h5 class="text-center text-lg"><?= $modelo; ?></h5>
        <img src="<?= $imagen ?>" alt="<?= $nombre; ?>" class="imagen_productos" />
      </div>
      <div class="containerDatos">
        <p class="mt-3"><strong>Precio:</strong> <span class="text-destructive"><?= $precio ?> $</span></p>
        <p><strong>Kilometraje:</strong> <?= $kilometros ?> km</p>
        <p><strong>Detalles:</strong> <?= $detalles ?></p>
        <h4 class="text-lg font-bold">Consultá por este vehículo:</h4>
        <form>
          <div class="mb-3">
            <label for="name" class="form-label">Nombre y apellido *</label>
            <input type="text" class="form-input" id="name" required />
          </div>
          <div class="mb-3">
            <label for="phone" class="form-label">Teléfono (opcional)</label>
            <input type="tel" class="form-input" id="phone" placeholder="Cód. área + número" />
          </div>
          <div class="mb-3">
            <label for="email" class="form-label">Email *</label>
            <input type="email" class="form-input" id="email" required />
          </div>
          <div class="mb-3">
            <label for="consulta" class="form-label">Consulta</label>
            <textarea class="form-input" id="consulta" rows="3"></textarea>
          </div>
          <button type="submit" class="btn btn-danger">REALIZAR CONSULTA</button>
        </form>
      </div>
    </div>
  </div>
<?php endif;
require 'templates/footer.phtml'; ?>

